### ISSUE TITLE
Error in intersections with 1 being added

### ISSUE THREAD

**Issue by SophieS9** [hms-dbmi/UpSetR#108]
Hi UpSetR team,

I'm trying out the upset R package as an alternative to (a lot of!) Venn diagrams and I've noticed an error in the intersections being produced. I've attached the data I'm using -
[RNA_upset_github.txt](https://github.com/hms-dbmi/UpSetR/files/1871516/RNA_upset_github.txt). I know that set "G" only has one item and this doesn't overlap with any of the items in "H" and "I". However when I run the following:

```
data<-read.table("./RNA_upset_github.txt", header=T, sep="\t")

upset(fromList(data), sets=c("G","H","I"), keep.order=T, empty.intersections = "on")
```

I'm getting the following figure, which shows a unique item in set "G" and an overlap between "G" and "H" of 1, which shouldn't be there. 
![upset_example pdf](https://user-images.githubusercontent.com/5912608/38250490-d32f74bc-3746-11e8-9acf-1b9e6072c43d.png)

I also know that between "D", "E" and "F" the intersect between all three groups should be 18, but it's showing 19. All of the other numbers have been calculated correctly. 

```
upset(fromList(data), sets=c("D","E","F"), keep.order=T, empty.intersections = "on")
```
![upset_example_2](https://user-images.githubusercontent.com/5912608/38250728-739b1ee2-3747-11e8-98f9-7b5e6b89b3aa.png)

Any ideas if I'm doing something wrong?

All the Best!

Sophie

**Comment by RichardJActon** [comment]
Hi @SophieS9,

There is some imperfect NA / Null value handling in the current `fromList()` function the reason you are getting this result is because the empty string value "" in your list is being considered a group that could be in each set.

You can fix this with:

    data <- read.table("./RNA_upset_github.txt",
                 header=T,
                 sep="\t",
                 stringsAsFactors = FALSE)

    upset(fromList(apply(data,2,function(x){x[x != ""]})),
      sets=c("G","H","I"),
      keep.order=T,
      empty.intersections = "on")

the `apply(data,2,function(x){x[x != ""]})` just selects all the elements in each column that are not empty strings and gives you back a named list of all the non-empty string groups for each set.

**Comment by SophieS9** [comment]
Great @RichardJActon, that makes sense and has fixed it! Thanks for the help!
