### ISSUE TITLE
Allow membership of multiple intersections?

### ISSUE THREAD

**Issue by pinin4fjords** [hms-dbmi/UpSetR#58]
Thank you for UpSet and UpSetR- very nice. 

I've been having some issues with interpretation, related to the fact that something can seemingly only be a member of one intersection. 

Example: I have a list of 14 sets with 1000s of entries in each. I was confused because the count shown for a dominant intersection between 4 of these sets was not quite right. I worked out that this was due to low counts in higher-degree intersections. 

Assuming I haven't missed something fundamental, is there a way of running the upset command in UpSetR such that the displayed count reflects the true size of the intersection, thereby allowing membership for an item in multiple intersections? Or would such a feature be feasible?

**Comment by ngehlenborg** [comment]
Since an UpSet plot always shows all possible (non-empty, if that is desired) intersections of _n_ sets, there are by definition no elements that are in more than one intersection in an UpSet plot. This is because the columns in an UpSet plot are equivalent to the areas of a Venn or Euler diagram. 

If you are interested in looking at aggregates of multiple intersections, then the interactive version of UpSet might be an option for you (from the open access paper: http://ieeexplore.ieee.org/document/6876017/?arnumber=6876017):

![screen shot 2016-11-13 at 4 29 09 pm](https://cloud.githubusercontent.com/assets/1216518/20249002/5d78ca1e-a9be-11e6-9e51-c518230df40f.png)

So while it is feasible to do this in principle and while we are supporting it in the interactive version of UpSet, we have not had the time (and enough requests) to add it to UpSetR. But I will take this a vote for intersection queries in UpSetR ... 👍

**Comment by pinin4fjords** [comment]
Ahh yes, obviously I misphrased things slightly ;-). But thank you for the reply.

I think what I would like is actually a bit simpler than what the interactive version does. I would just like every intersection illustrated to contain everything in that intersection, even if its members are also in one or more higher-order intersections. So diverging from the Venn/Euler idea. It could just be a bit of simple post-processing in response to a flag (though I haven't actually looked at the code!).

But fingers crossed for a future addition to UpSetR!

**Comment by pinin4fjords** [comment]
a 'P.S.' on interactivity: I see you have a Shiny app, and I have my own UpStart Shiny module as part of my applications. But what would be totally amazing would be Shiny integration of an interactive version, like Plotly et al do.

**Comment by pinin4fjords** [comment]
FYI I ended up coding this myself. I made a basic Shiny with an option for the display I was talking about, rendered using Shiny, to illustrate the point:

https://pinin4fjords.shinyapps.io/upset-shiny-plotly/
https://github.com/pinin4fjords/upset-shiny-plotly

Hope you don't mind these being up- I've made sure to add links back to 'UpSet proper'.

Jon

**Comment by kushtun** [comment]
Per above, I think it is critical for many uses to have the detailed info of the intersection queries available -- if doing, say, the gene comparisons, it's essentially useless to know that there are 3 genes of interest (which one gets with upsetR now) without knowing -- exactly which 3.

So yes, a vote to add that functionality from the web version to the R (and hence shiny-able) version, would make a powerful tool which could be shared.

Can I just repeat this entry a few hundred times more to make sure there are enough votes?
😃

**Comment by ngehlenborg** [comment]
This last comment is unrelated to the original question, but there is an answer: since are is simply not meant for interactive visualizations driven by the command line, we are currently not planning on adding interactive features to UpSetR. However, the issue described @kushtun's question can be addressed with attribute plots: https://cran.r-project.org/web/packages/UpSetR/vignettes/attribute.plots.html

In the example given, the attribute of interest is the name or symbol associated with the genes in a given intersection and a "plot" that could show this would be a simple list of labels. Not ideal but provides an answer to what is contained a given intersection.

@kushtun: please open a separate thread if you want further discussion.
