### ISSUE TITLE
Rotated bar labels off-center

### ISSUE THREAD

**Issue by msto** [hms-dbmi/UpSetR#70]
Hi,

When attempting to rotate the bar labels with `number.angles`, the text is moved off-center and intersects the bar beneath. Would it be possible to update the implementation of the `number.angles` parameter so a rotated label is centered above the below bar? 

I'm more of a python guy, so I don't know how to set the R equivalents behind the scenes, but setting the horizontal alignment to the equivalent of "left" if the rotation is >0 and vertical alignment to the equivalent of "bottom", then positioning the text at a point centered and slightly above the bar should achieve the behavior I'm asking for, if that helps clarify the request.

Thanks,

Matt

[demo_0.pdf](https://github.com/hms-dbmi/UpSetR/files/899840/demo_0.pdf)
[demo_90.pdf](https://github.com/hms-dbmi/UpSetR/files/899841/demo_90.pdf)

**Comment by JakeConway** [comment]
Hi Matt,

I think we settled on the default ggplot2 horizontal justification for the numbers above the intersection size bars due to how the numbers rotate when they are large and there is many intersections. If you want to clone the repo and play around with it by including `hjust` as a parameter  on line 133 of MainBar.R you might be able fine tune it. I believe `hjust = 0` is left anchor, `hjust = 0.5` is center anchor, and `hjust = 1` is right anchor
